### ISSUE TITLE
Mirrored screen Bug

### ISSUE THREAD

**Issue by GabrielBermudez123** [gta-chaos-mod/Trilogy-ASI-Script#127] opened 2021-03-26 13:32 UTC
When the effect come out, I see two triangles on my screen instead the normal effect ¿why?
CPU Features:
Motherboard A-320
Ryzen 5 1600x
RX 570 4gb
12gb ram ddr4

**Comment by Lebon14** [comment] 2021-07-21 20:33
> RX 570 4gb

There's your issue. Only works with nvidia cards.

**Comment by Lebon14** [comment] 2022-01-14 03:11
> 

Because Lordmau5 only had an nvdia card to test with. the code will be different for AMD dedicated, AMD integrated, Intel integrated and future intel dedicated. And nobody wants to develop the mod so...

**Comment by Lordmau5** [comment] 2022-04-07 05:46
Parik was kind enough to look into those effects again and supposedly got a fix for it that'll be arriving with the 3.0 rewrite we're both working on.

I sadly can't give an ETA on *when* that'll be since we effectively started working on it like... yesterday, but that's all I can say so far.

I did offer an updated version of the current mod to those that want to give it a try that don't have an NVIDIA card (so, AMD users, Intel integrated, etc.)

If you want to give it a try please contact me on Discord - Lordmau5#0001

**EDIT:**
Yup, just had it confirmed from people that had this issue that it's fixed in the newest version. :)

**Comment by Lordmau5** [comment] 2022-09-03 09:43
Fixed in v3.0.1

**Closed by Lordmau5** 2022-09-03 09:43 UTC
Labels: bug, fixed-in-dev
